### ISSUE TITLE
Shift Go Support Window to [1.18, 1.19]

### ISSUE THREAD

**Issue by shizhMSFT** [veraison/go-cose#102]
[Go 1.19](https://go.dev/blog/go1.19) is released with [release notes](https://go.dev/doc/go1.19)!

It is time to shift the window for go support to `[1.18, 1.19]` by updating

- `go. mod`
- GitHub Actions

**Comment by qmuntal** [comment]
The `go.mod` version directive is normally set to the minimum Go version supported by the module, although one can use a lower version if the module does not use any language feature not available on the lower version.

I would stick to `go1.18` and just change the GitHub Actions.
