### ISSUE TITLE
Where is the `cty` tag registered

### ISSUE THREAD

**Issue by OR13** [veraison/go-cose#105]
https://github.com/veraison/go-cose/blob/ebba05d25c1dc9a5eed3acf25446b7931291e1f4/headers_test.go#L31

Not showing up in this list: https://www.iana.org/assignments/cose/cose.xhtml

What is its integer mapping?

**Comment by qmuntal** [comment]
`cty` is an abbreviation for `content type`, which refers to a COSE header parameter with label 3.

**Comment by OR13** [comment]
![picard-face-palm](https://user-images.githubusercontent.com/8295856/193829319-9d5b5998-f638-4ef3-b68a-8b39eb7c22f0.gif)
