### ISSUE TITLE
Cut an v1.0.0-alpha.1 release

### ISSUE THREAD

**Issue by SteveLasker** [veraison/go-cose#12]
As we start to take dependencies on go-cose, we should cut a versioned release, and define the release process.
Adding a link to veraison/community#4 for defining a process.
- [x] Decide on main commit for a release [[8cef769](https://github.com/veraison/go-cose/commit/8cef769ef52c8fc111a8b1e4da83649f1cb170d0)](https://github.com/veraison/go-cose/commit/8cef769ef52c8fc111a8b1e4da83649f1cb170d0)
- [x]  Cut [branch named `v1.0.0-alpha.1`](https://github.com/veraison/go-cose/tree/v1.0.0-alpha.1) based on agreed upon main commit
- [x] Cut a [tag named `v1.0.0-alpha.1`](https://github.com/veraison/go-cose/releases/tag/v1.0.0-alpha.1)
- [x] Cut a [release named `v1.0.0-alpha.1`](https://github.com/veraison/go-cose/releases/tag/v1.0.0-alpha.1)
- [x] Update README.md

**Comment by SteveLasker** [comment]
Are we ready to cut the first alpha release? 
Please add +1

**Comment by shizhMSFT** [comment]
@SteveLasker Should we just version it `v0.1.0` as its version is tracked independent from `notation`, and it is less than `v1.0.0-alpha.1`?

**Comment by yogeshbdeshpande** [comment]
+1 so long as we have clarity and consensus on the release tag

**Comment by henkbirkholz** [comment]
so, we agreed on doing semver, right?

**Comment by SteveLasker** [comment]
v1.0.0-alpha.1 would make sense here. I was mixing other projects.

**Comment by SteveLasker** [comment]
@yogeshbdeshpande, @shizhMSFT, @henkbirkholz  can you **re**confirm the `v1.0.0-alpha.1` version?

**Comment by yogeshbdeshpande** [comment]
+1 from my side. I think, lets stick with v1.0.0-alpha.1 version and close this issue!

**Comment by henkbirkholz** [comment]
+1 for release

**Comment by thomas-fossati** [comment]
FYI https://go.dev/doc/modules/version-numbers

**Comment by SteveLasker** [comment]
With #65 complete, closing this issue
