### ISSUE TITLE
Change the default branch from master to main

### ISSUE THREAD

**Issue by SteveLasker** [veraison/go-cose#13]

**Comment by SteveLasker** [comment]
@thomas-fossati, @yogeshbdeshpande, @henkbirkholz any objections? @Shiwei already provided a 👍

**Comment by thomas-fossati** [comment]
> @thomas-fossati, @yogeshbdeshpande, @henkbirkholz any objections? @shiwei already provided a 👍

🚂 full steam ahead!

**Comment by henkbirkholz** [comment]
+1 master is weird

**Comment by SteveLasker** [comment]
Done, thanks folks.

**Comment by SteveLasker** [comment]
`master` is now named `main`
If you have a local clone, you can update it by running the following commands.
```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
