### ISSUE TITLE
Minor typo in godoc for UntaggedSign1Message

### ISSUE THREAD

**Issue by spennymac** [veraison/go-cose#149]
### What is the areas you experience the issue in?

Go-COSE Library

### What is not working as expected?

I was browsing the code and noticed a minor typo [here](https://github.com/veraison/go-cose/blob/354ac997519fe3d62314afe2906b106ef43bca5d/sign1.go#L265).

`UnataggedSign1Message` -> `UntaggedSign1Message.`

https://github.com/veraison/go-cose/pull/148/files

### What did you expect to happen?

N/A

### How can we reproduce it?

N/A

### Describe your environment

N/A

### What is the version of your Go-COSE Library?

 v1.1.0

**Comment by spennymac** [comment]
https://github.com/veraison/go-cose/pull/148

**Comment by SteveLasker** [comment]
Closing as #148 was merged
