### ISSUE TITLE
Is go-cose `v1.2.0` mis-released?

### ISSUE THREAD

**Issue by shizhMSFT** [veraison/go-cose#152]
### What is the areas you experience the issue in?

Go-COSE Library

### What is not working as expected?

dependabot sents PRs for upgrading `go-cose` from `v1.1.0` to `v1.2.0`. For instance: https://github.com/notaryproject/notation-go/pull/329

The [godoc for v1.2.0](https://pkg.go.dev/github.com/veraison/go-cose@v1.2.0) is available but there is no tag or release in this repo related to `1.2.0`.

@setrofim @yogeshbdeshpande @qmuntal @thomas-fossati Is `v1.2.0` mis-released? If so, we should [retract](https://go.dev/ref/mod#go-mod-file-retract) the release, and the next release should be `v1.3.0`.

### What did you expect to happen?

In `go.mod`, have an entry
```go
retract (
    v1.2.0 // Published accidentally.
    v1.2.1 // Contains retractions only.
)
```

### How can we reproduce it?

```console
PS D:\Test\go> go get github.com/veraison/go-cose
go: downloading github.com/veraison/go-cose v1.2.0
go: added github.com/fxamacker/cbor/v2 v2.4.0
go: added github.com/veraison/go-cose v1.2.0
go: added github.com/x448/float16 v0.8.4
```

### Describe your environment

All platforms

### What is the version of your Go-COSE Library?

v1.2.0

**Comment by shizhMSFT** [comment]
@setrofim I've noticed that #153 was merged. Would you like to tag b67457d00c55749e9e03b832d9f497c92f838061 as `v1.2.1`?

**Comment by shizhMSFT** [comment]
Closing this issue as `v1.2.0` has been successfully retracted.

<img width="608" alt="image" src="https://github.com/veraison/go-cose/assets/32161882/2cc088cb-bbeb-43b5-b463-e84d0a69cae9">

**Comment by orsenthil** [comment]
Even the 1.2.1 is retracted https://pkg.go.dev/github.com/veraison/go-cose?tab=versions
