### ISSUE TITLE
Improve error message for RS256, RS384, RS512 constants

### ISSUE THREAD

**Issue by roywill** [veraison/go-cose#164]
### What is the areas you experience the issue in?

Go-COSE Library

### What is not working as expected?

The error message could be better.

### What did you expect to happen?

Text string changed

### How can we reproduce it?

Attempting to use the constants for internal operations.

### Describe your environment

All

### What is the version of your Go-COSE Library?

V1.0

**Comment by hslatman** [comment]
Context: https://github.com/veraison/go-cose/pull/163#pullrequestreview-1572832541
