### ISSUE TITLE
Generate counter signatures

### ISSUE THREAD

**Issue by balena-zh** [veraison/go-cose#170]
### What is the areas you would like to add the new feature to?

Go-COSE Library

### Is your feature request related to a problem?

- One willing to attribute counter signatures to either `COSE_Sign1` or `COSE_Sign` will not find a way except fork the project and write alternative `toBeSigned` functions.

### What solution do you propose?

- Extend the current `Signature` struct adding a `CounterSign(rand io.Reader, signer Signer, protected cbor.RawMessage, payload, external []byte) error` so that the `toBeSigned` function receives also a `context` parameter that can be `"Signature"` or `"CounterSignature"`.

Above supports recursive counter signatures, where a counter signature also contains a counter signature.

### What alternatives have you considered?

- I considered implementing an external package extending `go-cose` but I had to copy-paste many private functions, such as `toBeSigned`, `deterministicBinaryString`, `marshal`, `ensureIV`, `ensureSigningAlgorithm`, and `ensureVerificationAlgorithm`, along with global variables `encMode`, `decMode`, `decModeWithTagsForbidden` and the `init()` function.

**Comment by balena** [comment]
Started to add such support in https://github.com/veraison/go-cose/pull/172

**Comment by balena** [comment]
Now #172 has been merged you may want to close this one @qmuntal
