### ISSUE TITLE
Make ToBeSigned publically accessible

### ISSUE THREAD

**Issue by honourfish** [veraison/go-cose#177]
### What is the areas you would like to add the new feature to?

Go-COSE Library

### Is your feature request related to a problem?

The cloud Key Management service I am using does NOT allow exporting of private key data.

In order to create the signature for the `cose_sign1` message I have to go through my cloud Key Management API.

Therefore I need the cose `ToBeSigned` to pass to my cloud Key Management API.

### What solution do you propose?

Be able to get cose `ToBeSigned` from a `cose_sign1` struct.

### What alternatives have you considered?

local implementation that generates cose `ToBeSigned` from the `cose_sign1` struct

**Comment by OR13** [comment]
Recommend to link to documentation on using custom signers, and close the issue as "asked, and answered".

**Comment by qmuntal** [comment]
Hi @honourfish. [cose.Sign1Message.Sign](https://pkg.go.dev/github.com/veraison/go-cose#Sign1Message.Sign) already supports custom signers via the `signer` parameter, which can be anything that implements the [cose.Signer](https://pkg.go.dev/github.com/veraison/go-cose#Signer) interface.

Note that the `cose.Signer` is called with the `ToBeSigned` passed in the `content` parameter, so you can already pass `ToBeSigned` to whatever cloud KMS you want.

**Comment by OR13** [comment]
I'm closing this issue, but if the answer above is not sufficient, please feel free to reopen.

**Comment by honourfish** [comment]
@qmuntal Yes thank you :) I missed the `cose.Signer` interface, I will use that for my KMS signing
