### ISSUE TITLE
Support for typ in protected header

### ISSUE THREAD

**Issue by OR13** [veraison/go-cose#184]
### What is the areas you would like to add the new feature to?

Go-COSE Library

### Is your feature request related to a problem?

I want to be able to use the `typ` header, as described in https://datatracker.ietf.org/doc/draft-ietf-cose-typ-header-parameter/

### What solution do you propose?

Add the code point for the `typ` parameter to the header parameters exposed by this library.

### What alternatives have you considered?

setting the parameter directly, without using the header parameters exposed by this library.

### Any additional context?

This should be done after https://datatracker.ietf.org/doc/draft-ietf-cose-typ-header-parameter/ has been assigned an RFC number.

**Comment by SteveLasker** [comment]
pending expert review of  https://datatracker.ietf.org/doc/draft-ietf-cose-typ-header-parameter/

**Comment by OR13** [comment]
As discussed on the call, we will hope open PRs for this issue and the cwt claims in headers issue until RFC numbers are assinged for both.
