### ISSUE TITLE
Add claims validation consistently

### ISSUE THREAD

**Issue by SteveLasker** [veraison/go-cose#186]
It could be argued this is essential to do, before merging this.

_Originally posted by @OR13 in https://github.com/veraison/go-cose/pull/183#discussion_r1467926710_

**Comment by OR13** [comment]
If we do validation, we should do it based on risk assessment.

- content type 
- x5t, x5c

There needs to be an argument for "why" we added extra validation logic.

And we need to be sure that we do not overstep the validation and create interoperability issues

**Comment by yogeshbdeshpande** [comment]
We should prioritise what validation we need to do.
It is un-realistic to do validation of `every` element , however certain elements are essential to be validated!

Need to do analysis of which one are a priority and then proceed with a PR!

**Comment by OR13** [comment]
Lets leave claims validation to the callers, and reduce the code we must maintain.
