### ISSUE TITLE
Cut v1.3.0-alpha.1 Release

### ISSUE THREAD

**Issue by SteveLasker** [veraison/go-cose#190]
@veraison/go-cose-maintainers, please +1 to create a `v1.2.0-alpha.1` release, or create/reference issues or new PRs that should be considered prior.

**Comment by SteveLasker** [comment]
@shizhMSFT, @setrofim, @qmuntal, @thomas-fossati, @yogeshbdeshpande, @roywill 
Please provide your vote for a release.

**Comment by shizhMSFT** [comment]
@SteveLasker Could you specify the commit proposed to be tagged as `v1.2.0-alpha.1`?

**Comment by SteveLasker** [comment]
Great question. We should make a template for releases 

Let’s start with: https://github.com/veraison/go-cose/commit/8c458e278da806b56444d1cbfd6ec24fc28aad9c

**Comment by yogeshbdeshpande** [comment]
+1 for release

**Comment by setrofim** [comment]
+1

**Comment by SteveLasker** [comment]
Released: https://github.com/veraison/go-cose/releases/tag/v1.2.0-alpha.1

**Comment by SteveLasker** [comment]
see #192

**Comment by shizhMSFT** [comment]
@SteveLasker @yogeshbdeshpande @setrofim It seems that `v1.2.0-alpha.1` is released. Note that as a golang library, it is released as long as there is a new tag no matter whether a release page is created or not.

I also noticed that we previously published `v1.2.0` in error and retracted it in `v1.2.1`. Technically, our next version should be `v1.3.0-alpha.1` not `v1.2.0-alpha.1`.

**Comment by shizhMSFT** [comment]
Linking
- #152 
- #153

**Comment by SteveLasker** [comment]
I saw the retraction after digging in. 
Does anyone have a concern jumping who v1.3.0-alpha.1 ?

**Comment by OR13** [comment]
We should make sure the latest release matches to the latest tag.

**Comment by SteveLasker** [comment]
Updated the title to reflect the updated version

**Comment by SteveLasker** [comment]
https://github.com/veraison/go-cose/releases/tag/v1.3.0-alpha.1
