### ISSUE TITLE
Update release-checklist.md

### ISSUE THREAD

**Issue by SteveLasker** [veraison/go-cose#192]
When releasing 1.2.0-alpha.1, I realized the `./release-checklist.md` file it outdated, calling for an update to:

> Bump up the Version in [internal/version/version.go](https://github.com/veraison/go-cose/blob/main/internal/version/version.go#L5) and open a PR for the changes.

`internal/version/version.go` doesn't exist.

We should update the release checklist before cutting the next release.

**Comment by shizhMSFT** [comment]
LoL. The release process docs are not well adapted to `go-cose` from `notation` in #188. I will send a PR to revise them.

/cc @FeynmanZhou @yizha1

**Comment by SteveLasker** [comment]
Yeah, i forgot the history of the docs.
