### ISSUE TITLE
Codecov for the `main` branch is not up to date

### ISSUE THREAD

**Issue by shizhMSFT** [veraison/go-cose#202]
Since the `CODECOV_TOKEN` is missing, the codecov percentage has not been updated after the commit 2b6f94f33749f8dbf96d199cfe7c498df431c6cf, although the codecov for PRs are working properly (this is because PRs to public repos does not require a token).

Error log from https://github.com/veraison/go-cose/actions/runs/10406856016/job/28820855042#step:5:31:
```console
Error: Codecov token not found. Please provide Codecov token with -t flag.
Warning: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
```

To fix it, admins of the `go-cose` repository are requested to set the `CODECOV_TOKEN` in the repository secret. Detailed workflow can be found in https://github.com/veraison/go-cose/pull/200#issuecomment-2291579651 and https://github.com/veraison/go-cose/pull/200#issuecomment-2291582018.

References:
- #199 
- #200

**Comment by SteveLasker** [comment]
Closing as #199 and #200 are resolved
