### ISSUE TITLE
Cut v1.3.0 release

### ISSUE THREAD

**Issue by SteveLasker** [veraison/go-cose#204]
If there are no issues on the [v1.3.0-rc.1]()https://github.com/veraison/go-cose/milestone/12 release, we will progress to `v1.3.0`

Delta since [v1.2.1](https://github.com/veraison/go-cose/compare/v1.2.1...v1.3.0-rc.1)

~There is a one [ReadMe](https://github.com/veraison/go-cose/issues/203) update to incorporate, then a commit will be provided to vote upon~

**Comment by SteveLasker** [comment]
Please vote to promote [v1.3.0-rc.1](https://github.com/veraison/go-cose/releases/tag/v1.3.0-rc.1), which is commit [e5c68f97dfbb7dc2677e891ceea9a8eafe42ddb4](https://github.com/veraison/go-cose/commit/e5c68f97dfbb7dc2677e891ceea9a8eafe42ddb4) to the final **v1.3.0** release.

To avoid reset, we will not pull in #206

**Comment by OR13** [comment]
Vote by putting a thumbs up.... if you object, leave a comment explaining why, and a thumbs down.

**Comment by thomas-fossati** [comment]
As a data point: we are using v1.3.0-rc.1 in veraison (ccatoken, psatoken and services) and found no problems with it.

**Comment by SteveLasker** [comment]
Completed with: https://github.com/veraison/go-cose/releases/tag/v1.3.0
