### ISSUE TITLE
Remove External property from Signature and Sign1Message

### ISSUE THREAD

**Issue by qmuntal** [veraison/go-cose#24]
See https://github.com/veraison/go-cose/pull/17#discussion_r841506954.

**Comment by shizhMSFT** [comment]
@qmuntal If we remove `External` in `Signature` and `Sign1Message`, where should we put it? In the `Sign()` and `Verify` as before?

**Comment by qmuntal** [comment]
> @qmuntal If we remove External in Signature and Sign1Message, where should we put it? In the Sign() and Verify as before?

Yep.

**Comment by shizhMSFT** [comment]
Addressed by #31
