### ISSUE TITLE
Headers.UnmarshalFromRaw accepts duplicated map keys

### ISSUE THREAD

**Issue by qmuntal** [veraison/go-cose#27]
https://datatracker.ietf.org/doc/html/rfc8152#section-14 says:

> Applications MUST NOT parse and process messages with the same label used twice as a key in a single map.

We are not enforcing this restriction.

This issue has been found by running negative conformance test `sign1-verify-negative-0002` and `sign1-verify-negative-0003` from #26

**Comment by shizhMSFT** [comment]
I need to check if https://github.com/fxamacker/cbor supports checking the duplicated key or not.

**Comment by shizhMSFT** [comment]
Looks like I can set `DupMapKeyEnforcedAPF` to resolve.

**Comment by shizhMSFT** [comment]
Addressed by #28
