### ISSUE TITLE
Algorithm Test Coverage

### ISSUE THREAD

**Issue by SteveLasker** [veraison/go-cose#36]
To support [Notary](https://github.com/notaryproject/notaryproject/blob/main/signature-specification.md#signature-algorithm-requirements), the following algorithms will need testing:

1. RSASSA-PSS with SHA-256
1. RSASSA-PSS with SHA-384
1. RSASSA-PSS with SHA-512
1. ECDSA on secp256r1 with SHA-256
1. ECDSA on secp384r1 with SHA-384
1. ECDSA on secp521r1 with SHA-512

**Comment by thomas-fossati** [comment]
I have added [4 new test cases to gluecose](https://github.com/gluecose/test-vectors/pull/12) to cover RSASSA-PSS with SHA-384 and RSASSA-PSS with SHA-512 signing and verification using Sign1.

**Comment by qmuntal** [comment]
> I have added [4 new test cases to gluecose](https://github.com/gluecose/test-vectors/pull/12) to cover RSASSA-PSS with SHA-384 and RSASSA-PSS with SHA-512 signing and verification using Sign1.

These new test cases have been integrated in #44

@SteveLasker we can close this issue. @shizhMSFT bumped the coverage ratio to 93.3% in #41.
