### ISSUE TITLE
Merge Remote Signing Branch into Main

### ISSUE THREAD

**Issue by SteveLasker** [veraison/go-cose#37]
To prepare for the Alpha.1 release, we'll

- [x] Complete the coding in the remote signing branch
- [x] Complete the test coverage, with passing tests
- [x] Create a tag [`v0.0.0-sign1-alpha.0`](https://github.com/veraison/go-cose/releases/tag/v0.0.0-sign1-alpha.0) and [`v0.0.0-sign1-alpha.0`](https://github.com/veraison/go-cose/tree/v0.0.0-sign1-alpha.0) branch from main, preserving the content prior to the remote signing updates
- [x] Identify PR #51 to merge into main
- [ ] Merge into main

**Comment by SteveLasker** [comment]
@shizhMSFT , is the first item complete, and we're working through tests and bugs?

**Comment by shizhMSFT** [comment]
@SteveLasker Yes, we are working on the tests and fixing bugs.
