### ISSUE TITLE
COSE_Sign1 and COSE_Sign should enforce major type 2 for the payload and the signature 

### ISSUE THREAD

**Issue by qmuntal** [veraison/go-cose#46]
Found via fuzzing.

`Sign1Message.UnmarshalCBOR` should reject the following message: `[]byte("҄D\xa1000\xa10X\x1e000000000000000000000000000000T00000000000000000000\x81\xf800")`,

Notice that the Signature property is an array with major type 4, but https://datatracker.ietf.org/doc/html/rfc8152#section-4.2 restricts it to major type 2.

@shizhMSFT

**Comment by shizhMSFT** [comment]
Nice catch. This is a tough one since `[]byte` can be interpreted as "a byte string" or "an array of bytes". It impacts `payload`, `signature`, and `protected` header.
