### ISSUE TITLE
Integrate with codecov.io

### ISSUE THREAD

**Issue by qmuntal** [veraison/go-cose#50]
We are currently doing some [nasty things](https://github.com/veraison/go-cose/blob/remote-signing/.github/workflows/ci-go-cover.yml#L36) to report the coverage. Coverage results are not stored anywhere and one never knows how the coverage changed from on PR to another.

I propose to integrate with https://codecov.io, which is a great and free service for monitoring and reporting code coverage.

It is easy to integrate with GH actions and with Go build-in coverage tooling.

I can't do the integration myself because someone with admin rights needs to log into codecov and do the setup.

**Comment by thomas-fossati** [comment]
Sounds like a good idea to me.

**Comment by thomas-fossati** [comment]
I have installed the codecov app on the Veraison org and enabled it for the go-cose repo.  @qmuntal please let me know if there's anything else you need from me.

**Comment by shizhMSFT** [comment]
Alternatively, we can leverage the existing `go tool cover` to generate coverage report, and `actions/upload-artifact` GitHub action to upload the report as artifacts.

**Comment by henkbirkholz** [comment]
So... what's it gonna be? :-) Thomas just incorporated codecov. Is there an active current best practice or is this by personal pref?

**Comment by qmuntal** [comment]
I don't have experience visualizing coverage reports via GitHub actions artifacts. @shizhMSFT do you know of any project doing it that way so I can see how it works?

**Comment by shizhMSFT** [comment]
@qmuntal [oras-go](https://github.com/oras-project/oras-go) is an example. You may download the coverage report [here](https://github.com/oras-project/oras-go/actions/runs/2172835119).

**Comment by SteveLasker** [comment]
@shizhMSFT, are you ok with moving to https://codecov.io/ on all related projects to have a consistent model?

**Comment by shizhMSFT** [comment]
Looks like we can directly add the codecov workflow to this repo since it is a public repo without admin rights.

**Comment by shizhMSFT** [comment]
> @shizhMSFT, are you ok with moving to https://codecov.io/ on all related projects to have a consistent model?

Yes, let's do this.

**Comment by SteveLasker** [comment]
Excellent, now we just need an owner to "make it so". 
Any takers?
