### ISSUE TITLE
Missing ed448 with EdDSA

### ISSUE THREAD

**Issue by tolginator** [veraison/go-cose#74]
Missing ed448 (security level 224 bits) to use with pure EdDSA for higher assurance applications where ed25519 (security level 128 bits) may be insufficient, such as RFC8032, Section 8.5.

File: go-cose/algorithm.go

**Comment by yogeshbdeshpande** [comment]
This seems like a Feature Request. Is this feature required for shipping version 1.0.0 ?

**Comment by qmuntal** [comment]
For reference, Go declined implementing ed448 either in `std` and `x/crypto`: https://github.com/golang/go/issues/29390.

**Comment by thomas-fossati** [comment]
CIRCL contains [an implementation](https://github.com/cloudflare/circl/tree/main/sign/ed448) that looks pretty solid.

**Comment by qmuntal** [comment]
`go-cose` already supports `ed448` via custom [cose.Signer](https://pkg.go.dev/github.com/veraison/go-cose#Signer).

I would avoid providing built-in signers and verifiers which are not part of the Go standard library or [x/crypto](https://github.com/golang/crypto).

For example, the following code snippet defines a signer and a verifier using `cloudflare/circl/sign/ed448`:

```go
import (
	"github.com/cloudflare/circl/sign/ed448"
	"github.com/veraison/go-cose"
)

type ed448Signer struct {
	key ed448.PrivateKey
}

func (ed *ed448Signer) Algorithm() cose.Algorithm {
	return cose.AlgorithmEd25519
}

func (ed *ed448Signer) Sign(rand io.Reader, digest []byte) ([]byte, error) {
	return ed448.Sign(ed.key, digest, ""), nil
}

type ed448Verifier struct {
	key ed448.PublicKey
}

func (ed *ed448Verifier) Algorithm() cose.Algorithm {
	return cose.AlgorithmEd25519
}

func (ed *ed448Verifier) Verify(digest []byte, signature []byte) error {
	if !ed448.Verify(ed.key, digest, signature, "") {
		return cose.ErrVerification
	}
	return nil
}

```

**Comment by yogeshbdeshpande** [comment]
@qmuntal to update the sample code above to comply with the post rc.1 interface.

**Comment by qmuntal** [comment]
> @qmuntal to update the sample code above to comply with the post rc.1 interface.

Done!

**Comment by SteveLasker** [comment]
Closing as @qmuntal updated the sample code, and no additional feedback.
