### ISSUE TITLE
Key extensibility support

### ISSUE THREAD

**Issue by shizhMSFT** [veraison/go-cose#9]
Currently, the siging key and the verification key must be a golang built-in type (e.g. `rsa.PrivateKey`).

We need to refactor the `go-cose` library so that `Signer` and `Verifier` are interfaces instead of solid structures. With those interface, other developers can make remote signing keys possible and even support FIPS 140-2 by using OpenSSL via CGO.

**Comment by thomas-fossati** [comment]
Sounds like a good idea.

**Comment by SteveLasker** [comment]
Agreed to move forward.
**Next steps:** review a design proposal. @shizhMSFT, do you want to provide that?

**Comment by shizhMSFT** [comment]
Addressed in #17
