### ISSUE TITLE
Create 1.0.0 Release

### ISSUE THREAD

**Issue by SteveLasker** [veraison/go-cose#98]
Complete the [1.0.0 release](https://github.com/veraison/go-cose/milestone/2)

High-level deliverables as follows:

- [x] Decide on main commit for a release (https://github.com/veraison/go-cose/commit/c5ba0da4875655e378aebd16654ad367c9c6edc4)
- [x] Cut a tag named `v1.0.0`
- [x] Update README.md

Before we ask for a +1 to cut the release, we're asking for a few of the dependent projects to confirm rc.1 is ready for a 1.0.0 release

~Can the maintainers please respond with a +1 comment once you are in favor of cutting this release?~

**Comment by SteveLasker** [comment]
Noting: https://github.com/notaryproject/notation-core-go/issues/37#issuecomment-1380690416 as confidence in the 1.0 release. There are some new feature requests, but these could come post 1.0. Providing a solid 1.0, with 2 public [security reviews completed](https://github.com/veraison/go-cose/tree/main/reports), speaks to our readiness.

**Comment by thomas-fossati** [comment]
We have been using the v1.0.0 release candidate in four different places for a while now, and there has been no problem except for https://github.com/veraison/go-cose/issues/115 which is now fixed in the main branch.  We are confident that main ([c5ba0da](https://github.com/veraison/go-cose/commit/c5ba0da4875655e378aebd16654ad367c9c6edc4)) is ready to ship.

**Comment by roywill** [comment]
We should release.

**Comment by SteveLasker** [comment]
@veraison/go-cose-maintainers, can you please give a +1 to cutting the 1.0 release based on https://github.com/veraison/go-cose/commit/c5ba0da4875655e378aebd16654ad367c9c6edc4?

**Comment by yogeshbdeshpande** [comment]
+1

**Comment by roywill** [comment]
+1
________________________________

**Comment by SteveLasker** [comment]
🎉 [v1.0.0](https://github.com/veraison/go-cose/releases/tag/v1.0.0)

**Comment by SteveLasker** [comment]
Remaining PR to update the readme: https://github.com/veraison/go-cose/pull/121

**Comment by SteveLasker** [comment]
Closing as 1.0 is released, and the readme is updated.
