### ISSUE TITLE
Numerous paths within `NewVerifier` make invalid casts, appear to have not be exercised in tests

### ISSUE THREAD

**Issue by dreemkiller** [veraison/go-cose#99]
In the `verifier.go` file, it appears that only the `case AlgorithmEd25519` has been tested.

This was discovered when attempting to call `NewVerifier` with `algo` set to `AlgorithmES256`. In that case, it attempts to cast `key` (type `crypto.PublicKey`) to `(*ecdsa.PublicKey)`. However, since it's casting a non-pointer to a pointer, it will always fail. 

The same situation is likely to occur when called with `algo` set to `AlgorithmPS256`, `AlgorithmPS384`, or `AlgorithmPS512`, as in those cases it attempts to case `key` to a pointer type as well (in this case, `(*rsa.PublicKey)`.

I have previously submitted a PR to fix this problem on an old version of the repo (https://github.com/veraison/go-cose/pull/95). The PR changes code in the `Verify` function, but this part of the code appears to have been moved to the `NewVerifier` function in the latest version.

**Comment by shizhMSFT** [comment]
As shown in the [code coverage report](https://app.codecov.io/gh/veraison/go-cose/blob/main/verifier.go) for `verifier.go`, all the cases are covered.

Note that `crypto.PublicKey` is an `interface` type, which can hold pointers.

Also, in golang, key types are different for each algorithm.
For RSA and ECDSA, keys are pointers.
For Ed25519, keys are `[]byte`, and internally they are pointers.

**Comment by shizhMSFT** [comment]
You may also want to check the golang doc for `crypto` packages.
- [crypto/rsa](https://pkg.go.dev/crypto/rsa#GenerateKey): `*rsa.PrivateKey`
- [crypto/ecdsa](https://pkg.go.dev/crypto/ecdsa#GenerateKey): `*ecdsa.PrivateKey`
- [crypto/ed25519](https://pkg.go.dev/crypto/ed25519#NewKeyFromSeed): `ed25519.PrivateKey`

**Comment by dreemkiller** [comment]
So, it's your **intention** that sometimes `NewVerifier` should be called with a pointer for `key`, and sometimes it should be called with a non-pointer, depending on the path within your function that we need to take?

I don't think the makes very much sense from an API point of view.

**Comment by yogeshbdeshpande** [comment]
@dreemkiller : I suppose @shizhMSFT has adequately clarified the golang aspect of the implementation. If there is no further issue, could you please close this github issue?

**Comment by dreemkiller** [comment]
I still have the unaddressed comment above: Is it your intention to have `NewVerifier` to sometimes be called with a pointer for `key`, and sometimes with a value for `key`, dependent upon the type of the underlying data in `key`? Because that's what it appears to need at the moment.

**Comment by henkbirkholz** [comment]
I think the answer is yes, as this is how `crypto` in go works? If we were to "change" that, it might be even more confusing. https://github.com/veraison/go-cose/issues/99#issuecomment-1219083559 highlights the current status.
